name: 'Create AWS EC2 instance'
description: 'Github action to create a new AWS EC2 instance in the cloud using passed through arguments'
inputs:
  access-key-id:
    description: 'The Access Key Id used to authenticate against AWS'
    required: true
    
  access-key-secret:
    description: 'The Access Key secret used to authenticate against AWS'
    required: true
  
  region:
    description: 'The region where the EC2 instance should get created'
    required: true

  image-id:
    description: 'Provide the Operating system image ID used on the EC2 instance [ubuntu, windows, aws-linux, ...]'
    required: true
    default: 'ami-0329d3839379bfd15'

  name:
    description: 'The name of the new EC2 instance'
    required: true

  instance-type:
    description: 'The Type of the new instance which should get launched [t2.micro, t2.medium, t5.xlarge, ...]'
    required: true
    default: 't2.micro'
  
  key-pair:
    description: 'Keypair which should get attached to the ec2 instance for SSH connection'
    required: false
  
  security-group-ids:
    description: 'The IDs of the Security Groups which should get attached to the new EC2 instance divided by comma'
    required: false
  
  volume-size:
    description: 'The size of the attached volume in Gib'
    required: false
    default: 8



# outputs:
runs:
  using: 'node16'
  main: action/index.js